=== jdngray77/FlightSimHelper/MSFSHelper.Core/Data/Checklists/ChecklistSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<!-- Root element -->
	<xs:element name="ChecklistGroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Checklists">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Checklist" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Items">
											<xs:complexType>
												<xs:sequence>
													<!-- StateMonitorChecklistItem definition -->
													<xs:element name="StateMonitorChecklistItem" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="Name" type="xs:string" use="required" />
															<xs:attribute name="Action" type="xs:string" use="required" />
															<xs:attribute name="Notes" type="xs:string" use="optional" />

															<xs:attribute name="VariableName" type="xs:string" use="required" />
															<xs:attribute name="RequiredValue" type="xs:string" use="required" />
															<xs:attribute name="DataOffset" type="xs:string" use="optional" />
															<xs:attribute name="Latching" type="xs:boolean" use="optional" />
														</xs:complexType>
													</xs:element>

													<!-- InformationalChecklistItem definition -->
													<xs:element name="InformationalChecklistItem" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:attribute name="Name" type="xs:string" use="required" />
															<xs:attribute name="Action" type="xs:string" use="required" />
															<xs:attribute name="Notes" type="xs:string" use="optional" />
														</xs:complexType>
													</xs:element>

												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Name" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jdngray77/FlightSimHelper/MSFSHelper.Core/Data/Checklists/A32NX Checklists.xml
<ChecklistGroup 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xsi:schemaLocation="http://www.w3.org ChecklistSchema.xsd"
	Name="A32NX">
	<Checklists>
		<Checklist Name="STARTING THE AIRCRAFT">
			<Items>
				<StateMonitorChecklistItem Name="PRK BRK" Action="ON" VariableName="A32NX_PARK_BRAKE_LEVER_POS" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="SPD BRK" Action="CHECK RET" VariableName="A32NX_SPOILERS_HANDLE_POSITION" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="FLAPS" Action="CHECK RET" VariableName="A32NX_FLAPS_HANDLE_INDEX" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="RX RADAR SYS" Action="OFF" VariableName="XMLVAR_A320_WEATHERRADAR_SYS" RequiredValue="0" Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="ENG MASTER 1" Action="OFF" VariableName="FUELSYSTEM VALVE SWITCH:1" DataOffset="0x66CB" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="ENG MASTER 2" Action="OFF" VariableName="FUELSYSTEM VALVE SWITCH:2" DataOffset="0x66CC" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="ENG MODE SEL" Action="NORM" VariableName="TURB ENG IGNITION SWITCH EX1:1" DataOffset="0x66CA" RequiredValue="1"/>
				
				<!-- TODO CONFIRM -->
				<InformationalChecklistItem Name="THRUST LVRS" Action="IDLE"/>
				<StateMonitorChecklistItem Name="L/G LVR" Action="DOWN" VariableName="GEAR HANDLE POSITION" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="WIPERS L" Action="OFF" VariableName="CIRCUIT SWITCH ON:77" DataOffset="0x66D2" RequiredValue="0"/>
				<StateMonitorChecklistItem Name="WIPERS R" Action="OFF" VariableName="CIRCUIT SWITCH ON:80" DataOffset="0x66D4" RequiredValue="0"/>
				
				<!-- TODO IF ELSE 'EXTERNAL POWER AVAILABLE'-->
				<StateMonitorChecklistItem Name="Battery 1" Action="SET AUTO" VariableName="A32NX_OVHD_ELEC_BAT_1_PB_IS_AUTO" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="Battery 2" Action="SET AUTO" VariableName="A32NX_OVHD_ELEC_BAT_2_PB_IS_AUTO" RequiredValue="1"/>
			
				<StateMonitorChecklistItem Name="EXT PWR" Action="ON" VariableName="EXTERNAL POWER ON" RequiredValue="0" Notes="[gray](inop)[/]"/>
				
				<StateMonitorChecklistItem Name="APU FIRE TEST" Action="PERFORM" VariableName="A32NX_FIRE_TEST_APU" Latching="true" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="APU MASTER" Action="ON" VariableName="A32NX_OVHD_APU_MASTER_SW_PB_IS_ON" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="APU" Action="START / AVAIL" VariableName="A32NX_OVHD_APU_START_PB_IS_AVAILABLE" RequiredValue="1"/>
				

				<InformationalChecklistItem Name="INT LIGHTS" Action="AS RQRD" />
				<StateMonitorChecklistItem Name="NAV &amp; LOGO LIGHTS" Action="ON" VariableName="LIGHT NAV" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="STROBE LIGHT" Action="ON" VariableName="LIGHT STROBE" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				
				<StateMonitorChecklistItem Name="ECAM RCL" Action="PRESS" VariableName="A32NX_BTN_RCL" Latching="true" RequiredValue="1"/>
				<InformationalChecklistItem Name="OIL QTY" Action="CHECK" />
				<InformationalChecklistItem Name="ACCU BRK PRESSURE" Action="CHECK" />
				<StateMonitorChecklistItem Name="RAIN REPEL L" Action="PRESS" VariableName="A32NX_RAIN_REPELLENT_LEFT_ON" Latching="true" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="RAIN REPEL R" Action="PRESS" VariableName="A32NX_RAIN_REPELLENT_RIGHT_ON" Latching="true" RequiredValue="1"/>
			
				<StateMonitorChecklistItem Name="APU BLEED" Action="ON" VariableName="A32NX_OVHD_PNEU_APU_BLEED_PB_IS_ON" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="PACK 1" Action="ON" VariableName="A32NX_OVHD_COND_PACK_1_PB_IS_ON" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="PACK 2" Action="ON" VariableName="A32NX_OVHD_COND_PACK_2_PB_IS_ON" RequiredValue="1"/>

				<StateMonitorChecklistItem Name="CREW SUPPLY" Action="ON" VariableName="PUSH_OVHD_OXYGEN_CREW" RequiredValue="1"/>
				
				<StateMonitorChecklistItem Name="ADIR 1" Action="NAV" VariableName="A32NX_OVHD_ADIRS_IR_1_MODE_SELECTOR_KNOB" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="ADIR 2" Action="NAV" VariableName="A32NX_OVHD_ADIRS_IR_2_MODE_SELECTOR_KNOB" RequiredValue="1"/>
				<StateMonitorChecklistItem Name="ADIR 3" Action="NAV" VariableName="A32NX_OVHD_ADIRS_IR_3_MODE_SELECTOR_KNOB" RequiredValue="1"/>
				
				<StateMonitorChecklistItem Name="FUEL QTY" Action="CHECK / UPLOAD" VariableName="A32NX_ECAM_SD_CURRENT_PAGE_INDEX" RequiredValue="5" Latching="true"/>
				
				<StateMonitorChecklistItem Name="SEAT BELTS" Action="ON" VariableName="CABIN SEATBELTS ALERT SWITCH" DataOffset="0x66CD" RequiredValue="1"/>
				<InformationalChecklistItem Name="SMOKING SIGN" Action="AUTO"/> <!-- inop VariableName="XMLVAR_SWITCH_OVHD_INTLT_NOSMOKING_Position" RequiredValue="1" -->
				<InformationalChecklistItem Name="EMER EXIT LT" Action="AUTO"/> <!-- inop VariableName="XMLVAR_SWITCH_OVHD_INTLT_EMEREXIT_POSITION" RequiredValue="1" -->
				
				<InformationalChecklistItem Name="CABIN ELEVATION" Action="CHECK AUTO" /> <!-- manual check -->

				<InformationalChecklistItem Name="CABIN TEMPERATURE" Action="CHECK" /> <!-- manual check -->

				<StateMonitorChecklistItem Name="FUEL PMP L 1" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:2" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="FUEL PMP L 2" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:5" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="FUEL PMP C 1" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:9" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="FUEL PMP C 2" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:10" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="FUEL PMP R 1" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:3" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				<StateMonitorChecklistItem Name="FUEL PMP R 2" Action="ON" VariableName="FUELSYSTEM PUMP SWITCH:6" RequiredValue="0"  Notes="[gray](inop)[/]"/>
				
				<InformationalChecklistItem Name="FMGS / CDU" Action="DASHED" />
				<StateMonitorChecklistItem Name="ALTIMETERS" Action="SET QNH" VariableName="XMLVAR_Baro1_Mode" RequiredValue="1"/>
				
				<StateMonitorChecklistItem Name="DOORS" Action="CHECK" VariableName="A32NX_ECAM_SD_CURRENT_PAGE_INDEX" RequiredValue="8" Latching="true"/>
			
				<InformationalChecklistItem Name="RADIO ACTIVE" Action="SET TO ATIS"/>
				<InformationalChecklistItem Name="RADIO STBY" Action="SET TO GROUND"/>
				
				<StateMonitorChecklistItem Name="FLIGHT DIR" Action="ON" VariableName="AUTOPILOT FLIGHT DIRECTOR ACTIVE" RequiredValue="0" Notes="[gray](inop)[/]"/>
				
				
			</Items>
		</Checklist>
		
		
			
		
		
		
		
			
				
				
				
				
				
		
		<Checklist Name="CONFIGURE THE MCDU">
			<Items>
				<!-- TODO Notes Column -->
				
				<InformationalChecklistItem Name="FLIGHT PLAN" Action="OBTAIN" Notes="i.e SimBrief. Import into tablet &amp; Little NavMap."/>
				
				<InformationalChecklistItem Name="IFR CLEARANCE" Action="OBTAIN FROM ATC" Notes="READBACK CHECKLIST :
																								 - Cleared to the destination via specified route in the filed flight plan.
																								 - Initial cleared altitude after departure.
																								 - Assigned SID for departure OR radar vectors
																								 - Assigned departing runway.
																								 - Transponder/squawk code.
																								 - Departure frequency."
				/>
				
				<InformationalChecklistItem Name="MCDU INIT A" Action="INIT REQUEST IF AVAIL" Notes="If using SimBrief or a dept and arriv airport were selected
																									 in MSFS then INIT REQUEST may be used. Otherwise, manually
																									 enter flight plan."/>
				<InformationalChecklistItem Name="MCDU INIT A" Action="COMPLETE" Notes="INIT A :
																						- FROM/TO
																						- FLT NBR
																						- COST INDEX
																						- WIND/TEMP > WIND REQUEST (for all phases)
																						- CRZ FL/TEMP
																						"/>
				
				<InformationalChecklistItem Name="MCDU F/PLAN" Action="COMPLETE" Notes="F/PLAN :
																						- CHK F/PLAN
																						- Enter SID/STARs
																						- Handle discontinuities
																						"/>
				
				<InformationalChecklistItem Name="MCDU SEC F/PLAN" Action="INOP"/>		
				
				
				<InformationalChecklistItem Name="MCDU RAD NAV" Action="COMPLETE" Notes="RAD NAV
																						- CHK AUTOTUNE. VERIFY USEFUL VOR.
																						- CHK DEPARTURE ILS
																						- CHK ARRIVAL ILS
																						"/>
				
				<InformationalChecklistItem Name="MCDU INIT B" Action="COMPLETE" Notes="INIT B
																						- ENTER ZFW/ZFWCG (FROM TABLET > PAYLOAD, OR AUTO-INSERT)
																						- FOB : EITHER INIT (LETS MCDU PRED FUEL), OR ENTER FROM FLIGHT PLAN.
																						"/>
				
				<InformationalChecklistItem Name="MCDU PERF" Action="COMPLETE" Notes="PERF :
																					  - CALC T/P PERF USING TABLET
																					  - FLEX TO TEMP
																					  - CW/FLAPS
																					  - TRANS ALT (IF PROVIDED IN F/PLAN)
																					  - V1/R/2 AUTO-INSERT
																						"/>
				
				<StateMonitorChecklistItem Name="ATC MODE" Action="STBY" VariableName="A32NX_TRANSPONDER_MODE" RequiredValue="0"/>
				<InformationalChecklistItem Name="SQUARK" Action="SET"/>
				
				
				<!-- todo -->
				<InformationalChecklistItem Name="ANTIICE" Action="AS RQRD"/>
				<InformationalChecklistItem Name="ECAM STATUS" Action="CHECK" />
				<InformationalChecklistItem Name="PITCH TRIM" Action="AS RQRD"/>
				<InformationalChecklistItem Name="RUDDER TRIM" Action="ZERO"  /> <!-- VariableName="XMLVAR_RUDDERTRIM" -->
 			</Items>
		</Checklist>
